# Generated by Django 4.2.1 on 2023-05-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Sate',
            new_name='State',
        ),
    ]
