# Generated by Django 4.2.1 on 2023-05-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_sate_record_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
