# Generated by Django 4.2.1 on 2023-05-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_create_at_record_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='State',
            new_name='state',
        ),
    ]
